### ISSUE TITLE
Can sent messages to non-whataspp number

### ISSUE THREAD

**Issue by Tsjippy** [gajosu/ha-whatsapp-web-rest-api#183]
### Description of the issue

Using this add on you can send a message to any number. The result will not indicate a failure. This is a bug. Can we fix that?

### Addon version

2.4.0

### Platform

 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.2

### Logs of the issue (if applicable)

 {'id': {'fromMe': True, 'remote': 'INVALIDNUMBER@c.us', 'id': '3EB066F8406D07F61A1CE1', '_serialized': 'true_INVALIDNUMBER@c.us_3EB066F8406D07F61A1CE1'}, 'viewed': False, 'body': 'THEMESSAGE', 'type': 'chat', 't': 1732340437, 'from': {'server': 'c.us', 'user': 'MYNUMBER', '_serialized': 'MYNUMBER@c.us'}, 'to': {'server': 'c.us', 'user': 'INVALIDNUMBER', '_serialized': 'INVALIDNUMBER@c.us'}, 'ack': 0, 'isNewMsg': True, 'star': False, 'kicNotified': False, 'isFromTemplate': False, 'pollInvalidated': False, 'isSentCagPollCreation': False, 'latestEditMsgKey': None, 'latestEditSenderTimestampMs': None, 'mentionedJidList': [], 'groupMentions': [], 'isEventCanceled': False, 'eventInvalidated': False, 'isVcardOverMmsDocument': False, 'isForwarded': False, 'hasReaction': False, 'productHeaderImageRejected': False, 'lastPlaybackProgress': 0, 'isDynamicReplyButtonsMsg': False, 'isCarouselCard': False, 'parentMsgId': None, 'isMdHistoryMsg': False, 'stickerSentTs': 0, 'isAvatar': False, 'lastUpdateFromServerTs': 0, 'invokedBotWid': None, 'bizBotType': None, 'botResponseTargetId': None, 'botPluginType': None, 'botPluginReferenceIndex': None, 'botPluginSearchProvider': None, 'botPluginSearchUrl': None, 'botPluginSearchQuery': None, 'botPluginMaybeParent': False, 'botReelPluginThumbnailCdnUrl': None, 'botMsgBodyType': None, 'requiresDirectConnection': None, 'bizContentPlaceholderType': None, 'hostedBizEncStateMismatch': False, 'senderOrRecipientAccountTypeHosted': False, 'placeholderCreatedWhenAccountIsHosted': False, 'links': []}

**Comment by gajosu** [comment]
Hi, the library has the `client.isRegisteredUser(id)` method to check it, but it is not implemented in this API, feel free to do a PR if you want to implement it!

https://docs.wwebjs.dev/Client.html#isRegisteredUser

**Comment by Tsjippy** [comment]
> Hi, the library has the `client.isRegisteredUser(id)` method to check it, but it is not implemented in this API, feel free to do a PR if you want to implement it!
> 
> https://docs.wwebjs.dev/Client.html#isRegisteredUser

Done!
https://github.com/gajosu/ha-whatsapp-web-rest-api/pull/184

**Comment by gajosu** [comment]
Fixed in v2.4.1
